version: '3.7'

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    command: uvicorn main:app --reload --port ${PORT} --host 0.0.0.0
    restart: always
    volumes:
      - .:/usr/back-rpg-brenner
    ports:
      - ${PORT}:${PORT}
